!define RIDE_PROGID "R-IDE.CodeFile"

!macro RIDE_REGISTER_EXTENSION EXT
  WriteRegStr SHCTX "Software\Classes\.${EXT}\OpenWithProgids" "${RIDE_PROGID}" ""
  WriteRegStr SHCTX "Software\Classes\Applications\${MAINBINARYNAME}.exe\SupportedTypes" ".${EXT}" ""
  WriteRegStr SHCTX "Software\R-IDE\Capabilities\FileAssociations" ".${EXT}" "${RIDE_PROGID}"
!macroend

!macro RIDE_UNREGISTER_EXTENSION EXT
  DeleteRegValue SHCTX "Software\Classes\.${EXT}\OpenWithProgids" "${RIDE_PROGID}"
  DeleteRegValue SHCTX "Software\Classes\Applications\${MAINBINARYNAME}.exe\SupportedTypes" ".${EXT}"
  DeleteRegValue SHCTX "Software\R-IDE\Capabilities\FileAssociations" ".${EXT}"
!macroend

!macro RIDE_REGISTER_EXTENSIONS
  !insertmacro RIDE_REGISTER_EXTENSION "bash"
  !insertmacro RIDE_REGISTER_EXTENSION "bat"
  !insertmacro RIDE_REGISTER_EXTENSION "c"
  !insertmacro RIDE_REGISTER_EXTENSION "cc"
  !insertmacro RIDE_REGISTER_EXTENSION "cjs"
  !insertmacro RIDE_REGISTER_EXTENSION "cmd"
  !insertmacro RIDE_REGISTER_EXTENSION "code-workspace"
  !insertmacro RIDE_REGISTER_EXTENSION "cpp"
  !insertmacro RIDE_REGISTER_EXTENSION "cs"
  !insertmacro RIDE_REGISTER_EXTENSION "css"
  !insertmacro RIDE_REGISTER_EXTENSION "cts"
  !insertmacro RIDE_REGISTER_EXTENSION "cxx"
  !insertmacro RIDE_REGISTER_EXTENSION "fish"
  !insertmacro RIDE_REGISTER_EXTENSION "go"
  !insertmacro RIDE_REGISTER_EXTENSION "h"
  !insertmacro RIDE_REGISTER_EXTENSION "hpp"
  !insertmacro RIDE_REGISTER_EXTENSION "htm"
  !insertmacro RIDE_REGISTER_EXTENSION "html"
  !insertmacro RIDE_REGISTER_EXTENSION "ini"
  !insertmacro RIDE_REGISTER_EXTENSION "java"
  !insertmacro RIDE_REGISTER_EXTENSION "js"
  !insertmacro RIDE_REGISTER_EXTENSION "json"
  !insertmacro RIDE_REGISTER_EXTENSION "jsonc"
  !insertmacro RIDE_REGISTER_EXTENSION "jsx"
  !insertmacro RIDE_REGISTER_EXTENSION "kt"
  !insertmacro RIDE_REGISTER_EXTENSION "kts"
  !insertmacro RIDE_REGISTER_EXTENSION "less"
  !insertmacro RIDE_REGISTER_EXTENSION "mjs"
  !insertmacro RIDE_REGISTER_EXTENSION "md"
  !insertmacro RIDE_REGISTER_EXTENSION "markdown"
  !insertmacro RIDE_REGISTER_EXTENSION "mts"
  !insertmacro RIDE_REGISTER_EXTENSION "properties"
  !insertmacro RIDE_REGISTER_EXTENSION "ps1"
  !insertmacro RIDE_REGISTER_EXTENSION "psm1"
  !insertmacro RIDE_REGISTER_EXTENSION "py"
  !insertmacro RIDE_REGISTER_EXTENSION "pyw"
  !insertmacro RIDE_REGISTER_EXTENSION "qmd"
  !insertmacro RIDE_REGISTER_EXTENSION "r"
  !insertmacro RIDE_REGISTER_EXTENSION "rmd"
  !insertmacro RIDE_REGISTER_EXTENSION "rs"
  !insertmacro RIDE_REGISTER_EXTENSION "scss"
  !insertmacro RIDE_REGISTER_EXTENSION "sh"
  !insertmacro RIDE_REGISTER_EXTENSION "sql"
  !insertmacro RIDE_REGISTER_EXTENSION "svelte"
  !insertmacro RIDE_REGISTER_EXTENSION "theia-workspace"
  !insertmacro RIDE_REGISTER_EXTENSION "toml"
  !insertmacro RIDE_REGISTER_EXTENSION "ts"
  !insertmacro RIDE_REGISTER_EXTENSION "tsx"
  !insertmacro RIDE_REGISTER_EXTENSION "vue"
  !insertmacro RIDE_REGISTER_EXTENSION "xml"
  !insertmacro RIDE_REGISTER_EXTENSION "yaml"
  !insertmacro RIDE_REGISTER_EXTENSION "yml"
  !insertmacro RIDE_REGISTER_EXTENSION "zsh"
!macroend

!macro RIDE_UNREGISTER_EXTENSIONS
  !insertmacro RIDE_UNREGISTER_EXTENSION "bash"
  !insertmacro RIDE_UNREGISTER_EXTENSION "bat"
  !insertmacro RIDE_UNREGISTER_EXTENSION "c"
  !insertmacro RIDE_UNREGISTER_EXTENSION "cc"
  !insertmacro RIDE_UNREGISTER_EXTENSION "cjs"
  !insertmacro RIDE_UNREGISTER_EXTENSION "cmd"
  !insertmacro RIDE_UNREGISTER_EXTENSION "code-workspace"
  !insertmacro RIDE_UNREGISTER_EXTENSION "cpp"
  !insertmacro RIDE_UNREGISTER_EXTENSION "cs"
  !insertmacro RIDE_UNREGISTER_EXTENSION "css"
  !insertmacro RIDE_UNREGISTER_EXTENSION "cts"
  !insertmacro RIDE_UNREGISTER_EXTENSION "cxx"
  !insertmacro RIDE_UNREGISTER_EXTENSION "fish"
  !insertmacro RIDE_UNREGISTER_EXTENSION "go"
  !insertmacro RIDE_UNREGISTER_EXTENSION "h"
  !insertmacro RIDE_UNREGISTER_EXTENSION "hpp"
  !insertmacro RIDE_UNREGISTER_EXTENSION "htm"
  !insertmacro RIDE_UNREGISTER_EXTENSION "html"
  !insertmacro RIDE_UNREGISTER_EXTENSION "ini"
  !insertmacro RIDE_UNREGISTER_EXTENSION "java"
  !insertmacro RIDE_UNREGISTER_EXTENSION "js"
  !insertmacro RIDE_UNREGISTER_EXTENSION "json"
  !insertmacro RIDE_UNREGISTER_EXTENSION "jsonc"
  !insertmacro RIDE_UNREGISTER_EXTENSION "jsx"
  !insertmacro RIDE_UNREGISTER_EXTENSION "kt"
  !insertmacro RIDE_UNREGISTER_EXTENSION "kts"
  !insertmacro RIDE_UNREGISTER_EXTENSION "less"
  !insertmacro RIDE_UNREGISTER_EXTENSION "mjs"
  !insertmacro RIDE_UNREGISTER_EXTENSION "md"
  !insertmacro RIDE_UNREGISTER_EXTENSION "markdown"
  !insertmacro RIDE_UNREGISTER_EXTENSION "mts"
  !insertmacro RIDE_UNREGISTER_EXTENSION "properties"
  !insertmacro RIDE_UNREGISTER_EXTENSION "ps1"
  !insertmacro RIDE_UNREGISTER_EXTENSION "psm1"
  !insertmacro RIDE_UNREGISTER_EXTENSION "py"
  !insertmacro RIDE_UNREGISTER_EXTENSION "pyw"
  !insertmacro RIDE_UNREGISTER_EXTENSION "qmd"
  !insertmacro RIDE_UNREGISTER_EXTENSION "r"
  !insertmacro RIDE_UNREGISTER_EXTENSION "rmd"
  !insertmacro RIDE_UNREGISTER_EXTENSION "rs"
  !insertmacro RIDE_UNREGISTER_EXTENSION "scss"
  !insertmacro RIDE_UNREGISTER_EXTENSION "sh"
  !insertmacro RIDE_UNREGISTER_EXTENSION "sql"
  !insertmacro RIDE_UNREGISTER_EXTENSION "svelte"
  !insertmacro RIDE_UNREGISTER_EXTENSION "theia-workspace"
  !insertmacro RIDE_UNREGISTER_EXTENSION "toml"
  !insertmacro RIDE_UNREGISTER_EXTENSION "ts"
  !insertmacro RIDE_UNREGISTER_EXTENSION "tsx"
  !insertmacro RIDE_UNREGISTER_EXTENSION "vue"
  !insertmacro RIDE_UNREGISTER_EXTENSION "xml"
  !insertmacro RIDE_UNREGISTER_EXTENSION "yaml"
  !insertmacro RIDE_UNREGISTER_EXTENSION "yml"
  !insertmacro RIDE_UNREGISTER_EXTENSION "zsh"
!macroend

!macro NSIS_HOOK_POSTINSTALL
  WriteRegStr SHCTX "Software\Classes\${RIDE_PROGID}" "" "R-IDE Code File"
  WriteRegStr SHCTX "Software\Classes\${RIDE_PROGID}\DefaultIcon" "" "$\"$INSTDIR\${MAINBINARYNAME}.exe$\",0"
  WriteRegStr SHCTX "Software\Classes\${RIDE_PROGID}\shell\open" "" "Open with R-IDE"
  WriteRegStr SHCTX "Software\Classes\${RIDE_PROGID}\shell\open\command" "" "$\"$INSTDIR\${MAINBINARYNAME}.exe$\" $\"%1$\""
  WriteRegStr SHCTX "Software\Classes\Applications\${MAINBINARYNAME}.exe\shell\open\command" "" "$\"$INSTDIR\${MAINBINARYNAME}.exe$\" $\"%1$\""
  WriteRegStr SHCTX "Software\R-IDE\Capabilities" "ApplicationName" "R-IDE"
  WriteRegStr SHCTX "Software\R-IDE\Capabilities" "ApplicationDescription" "R-IDE code editor"
  WriteRegStr SHCTX "Software\RegisteredApplications" "R-IDE" "Software\R-IDE\Capabilities"
  !insertmacro RIDE_REGISTER_EXTENSIONS
  System::Call "shell32::SHChangeNotify(i,i,i,i) (0x08000000, 0x1000, 0, 0)"
!macroend

!macro NSIS_HOOK_PREUNINSTALL
  !insertmacro RIDE_UNREGISTER_EXTENSIONS
  DeleteRegValue SHCTX "Software\RegisteredApplications" "R-IDE"
  DeleteRegKey SHCTX "Software\R-IDE\Capabilities"
  DeleteRegKey /ifempty SHCTX "Software\R-IDE"
  DeleteRegKey SHCTX "Software\Classes\Applications\${MAINBINARYNAME}.exe"
  DeleteRegKey SHCTX "Software\Classes\${RIDE_PROGID}"
  System::Call "shell32::SHChangeNotify(i,i,i,i) (0x08000000, 0x1000, 0, 0)"
!macroend
